steps:
  - name: node:18.12.1
    entrypoint: npm
    args: ["install"]
  - name: node:18.12.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "AUTH=${_AUTH}"
      - "PORT=${_PORT}"
      - "TEST=${_TEST}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["create-env", "app", "deploy"]
timeout: "1600s"
